export const SET_QUERY = "SET_QUERY";
export const SET_SUGGESTIONS = "SET_SUGGESTIONS";
export const SET_PHOTOS = "SET_PHOTOS";
export const SET_PHOTOS_ERROR = "SET_PHOTOS_ERROR";
export const SET_PHOTOS_LOADING = "SET_PHOTOS_LOADING";
export const SET_CLEAR = "SET_CLEAR";